/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemojava_Main */

#ifndef _Included_jnidemojava_Main
#define _Included_jnidemojava_Main
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class jnidemojava_Main_JNIFunction */

#ifndef _Included_jnidemojava_Main_JNIFunction
#define _Included_jnidemojava_Main_JNIFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemojava_Main_JNIFunction
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jnidemojava_Main_00024JNIFunction_multiply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jnidemojava_Main_JNIFunction
 * Method:    nativeIntegrate
 * Signature: (DD[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_jnidemojava_Main_00024JNIFunction_nativeIntegrate
  (JNIEnv *, jobject, jdouble, jdouble, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
